# 导入库

In [5]:
import numpy as np

### 数组的创建和输出

In [6]:
a = np.array([1, 2, 3])      #一维数组的创建
b = np.array([[1,2], [3,4]])   #二位数组的创建
c = np.array([1,2,3], dtype=float)  #指定数据类型的创建

#### 打印数组

In [7]:
print(a)
print(b)
print(c)

[1 2 3]
[[1 2]
 [3 4]]
[1. 2. 3.]


### 数据类型

In [8]:
strings = np.array(['Hello', 'World', 'Python'])
print(strings)

number = np.array([1, 2, 3] ,dtype=str)    #通过dtype将数组中原本的int行转化为字符串形存储
print(type(number[0]))

['Hello' 'World' 'Python']
<class 'numpy.str_'>


### 数组的属性

In [9]:
a = np.array([1, 2, 3], dtype=float)

print("a ndim:",a.ndim)
print("a shape",a.shape)
print("a size",a.size)
print("a dtype",a.dtype)
print("a itemsize:",a.itemsize,"bytes")
print("a nbytes:",a.nbytes,"bytes")
print("a flags:",a.flags)

a ndim: 1
a shape (3,)
a size 3
a dtype float64
a itemsize: 8 bytes
a nbytes: 24 bytes
a flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



数组的维度                  ndim  
数组的每个维度大小           shape    
数组的元素个数               size = ndim * shape

#### 复述的输出

In [10]:
a = np.array([complex(2, 4), complex(3, 5)])
print(a.real)            #输出a的实部
print(a.imag)            #输出a的虚部

[2. 3.]
[4. 5.]


### 数据类型的转化

In [11]:
a = np.array([1, 2, 3],dtype=np.int16)
print(a.dtype)
print(a)
b = a.astype(np.float64)
print(b.dtype)
print(b)

int16
[1 2 3]
float64
[1. 2. 3.]


### 快速创建数组

#### 用0/1填充

In [12]:
a = np.zeros((2,3), dtype = np.float64)      #二行三列
print(a)


a = np.ones((4,4), dtype = np.float64)  
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 创建单位矩阵

In [13]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 创建随机数组

In [14]:
print(np.random.rand(2,3))   #创建二行三列的，样本位于[0,1)的数组
print(np.random.randint(1,10,size=(2,3)))   #创建二行三列的，样本位于[1,10)的数组
print(np.random.randn(2,3))   #创建二行三列的，样本位于标准正态分布的数组

[[0.2294677  0.33682736 0.76354695]
 [0.50598946 0.70683018 0.14299306]]
[[5 9 9]
 [8 3 2]]
[[ 1.17753835 -0.16992359  1.09039837]
 [ 0.41140873 -0.32093429  1.01442135]]


#### 从指定数值范围创建

In [15]:
x = np.arange(start=0, stop=10, step=1)
print(x)
#创建从0开始，到10结束，步长为1的数组。注：不包含stop的值。

[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(np.linspace(1, 10, 5))    #1-10之间的等差数列，5个元素

[ 1.    3.25  5.5   7.75 10.  ]
